"""
Django settings for proyecto_django project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# settings.py
import firebase_admin
from firebase_admin import credentials

# Configuración Firebase
FIREBASE_CREDENTIALS = {
  "type": "service_account",
  "project_id": "consultorio-raul",
  "private_key_id": "1b62200ffce3cf5333e96214cd0d0a6052e40fa3",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDcs5WtC4zyIDzY\nGr8jWjf4K6+AICs8p4B0c8mKC2wwgWrZFtCu6hsInBlkKjCxa3ilxhBFH/ZaixQq\nWpjkSb8H55n2ty3dAr54r01DE9yV5u0j95GU0lxZuNJFqC3nMZuS7X2r0qSdLM2h\nEqJv9xMTIQv3emtFdLhYe7d9P8OvzP3CHrdG4DI9S0A1CJ3ajuOkQJzxP4ck4tGI\n9gxi1AYUTLgVbsSoqV2wZjBj0lzZXJJbeGWCain4UJ0TKdu2MC7A/r7gbHI3dxGm\nWYqW0YyrIZA6OCjEnXNiLYAZa9cTuE7bGx7+l7JaJ15YYuJD4yZg+d0rJI2h+aE1\nNYgA7lGpAgMBAAECggEAF0Vy3/oesKWsULuiQaGo0ujVUrDhqj29vlm6q60IaYVt\n7SnaE4WBF/twtHZ756tNv4oWy1kjTnkJhW1D35d0lopp2kFGq14XlC1k29Cvctl0\nkhUv0zXKsdW6i0iAXZdGIJwc4xYdECsqHAS1XtG6P8s9YikVAE/+Q6s45fKoKURF\nj2/bWu93e+HgYKU/cKQOMn9bmqZB6inJzSUmfjNixx4REwk8HWJl4mPazgxSEEiC\nYR/ky51j9N04FiQKaI5HJJRr9p77GSY5jac9ofi/ymtHnQny9aX8pd0X+1LqGqzE\n1Ql7Ld41rwl4HyF//2Q0na0bCojOKytXAlJyKO3vUQKBgQD/qJMVWtJcjMApAImP\nVce7qBzb/Bv8tqXJ8SEjwtZzhZZP8+NvCX08AmphJW6SF/XjHA57EQDdiR59cTTi\nHU6BYj4xdTWDnrvKbYyOPn9oM9uEe/7GBSlwD9Iy01ZMHa/jkP0GT1ASzvCRS5Fl\n6Cmj8IrgQbRBYuuVaRsDphxNUQKBgQDc/w5hGFgdS54LNx82KWegNwWXEV0SBo7w\nagfxf5DrCVb3FjXxbCjwt7aStb3vHwzQl9rfCYhlVWQ9MOqYgYf8m2OW0nx9vb3/\nicpUu6BZpeqOOZMuF838ciy0O0jXBs0AiRaeeyH7mkR6l3/KXxQ6yt9eDySdeFT3\n2yVUlZJI2QKBgQCIesuaONPYCGOE//5vgFGSAlr1rQ6byD2VIp6YYqjtHsFxiTc+\nzYgHgxqbJcpzP0tKpG2ukRMvMMYQHWEn3JFOTM36xSF+VDzYAcdpIEAPtq9XeII3\n4AWRB0ElVODa3XZKO9p3hduvTr3qMrc5+chQ9laNBUZfKZmuN1/ugLzXIQKBgDlI\nFxcNs1Esl3N6vylPxB9gA5/rjT8t2gDwysxK72osipES/bps+ZOjWrxeRTPkzXKH\n2eBz3Rm+73N46WXMNU5BjKe8OS5ybvv8YChkVaTG/6wLul15KBgmE/ZHY5LwnVRl\nNCqx6dYIX3WTLTlsOZcfnJQJwsjaNtPjxqJM/pTJAoGBAK7g27N+jhHSr7HKZVa4\n8AIPV0Zy9hPyz7nD97C7nAutyM1KdqG9xmi5jmIJo4VxbmqSP3OIm2zqQ2WfQW5J\ny8OF5yPJSvyRVIHtvSix1EfYsmYBGS0SlLXv8nnSq3YXgHf78yeuUN80cz0550nY\nn8eE4NJXyvwAubq9idM+BzFv\n-----END PRIVATE KEY-----\n",
  "client_email": "firebase-adminsdk-fbsvc@consultorio-raul.iam.gserviceaccount.com",
  "client_id": "100750241269893941415",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40consultorio-raul.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}

cred = credentials.Certificate(FIREBASE_CREDENTIALS)
firebase_admin.initialize_app(cred)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

AUTH_USER_MODEL = 'admin_panel.CustomUser'



# Configuración de URLs
ROOT_URLCONF = 'proyecto_django.urls'

# Configuración de login
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'


# settings.py

# Configuración de correo
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Para Gmail
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'leonelvitto.777@gmail.com'  # Cambiar por tu correo
EMAIL_HOST_PASSWORD = 'plzj tizr uhvk fvvz'  # Usar contraseña de aplicación
DEFAULT_FROM_EMAIL = 'Recetas Médicas <leonelvitto.777@gmail.com>'

# Configuración adicional para Gmail
# (Necesitarás habilitar "Acceso de aplicaciones menos seguras" o usar OAuth2)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)gkmm8_k8k(qi*69_zy@aewbp$1uu@0f2ubl4z(ex=2z-u@_mw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'admin_panel', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# Configuración CSRF (agrega estas líneas si no las tienes)
CSRF_COOKIE_AGE = 31449600  # 1 año
CSRF_COOKIE_DOMAIN = None
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_PATH = '/'
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False  # Cambia a True si usas HTTPS
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS = []
CSRF_USE_SESSIONS = False


ROOT_URLCONF = 'proyecto_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'admin_panel/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Configuración de archivos estáticos
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'admin_panel/static'),
]

# Configuración para producción (agregar al final)
if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
